# Generated by Django 5.2 on 2025-05-01 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'verbose_name_plural': 'todo'},
        ),
        migrations.AlterModelTable(
            name='todo',
            table='todo',
        ),
    ]
