# Generated by Django 5.2 on 2025-05-10 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_todo_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='user_id',
            new_name='user',
        ),
    ]
